package View;

import Service.CustomerDao;
import Service.ImageOperations;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import Model.Address;
import Model.Customer;
import Service.AutoIDService;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class AddCustomer extends javax.swing.JInternalFrame {

	byte[] userimage = null;
	CustomerDao cDao = new CustomerDao();
	
	/**
	 * Creates new form AddCustomer
	 */
	public AddCustomer() {
		initComponents();
		autoID();
	}

	// Generates an ID for a new customer.
	private void autoID() {
		String id = AutoIDService.generateAutoID("customer", "CS");
		txtid.setText(id);
	}

//	// Validates a customer name to only contain letters, dashes, and apostrophes, as well as be at least 1 character.
//	public boolean validateCustomerName(String name) {
//		return name.matches("^[a-zA-Z'-]+$");
//	}
//	
//	// Validates a customer phone number to only allow numerical values. Must be 7 digits.
//	public boolean validateContact(String contact) {
//		return contact.matches("^[0-9]{7}$");
//	}
	
	/*
	// TODO add address formatting regex checks
	public boolean validateAddress(String address, String street, String city, String region, String zip, String country) {
		boolean isValid = false;
		
		if (address.matches("")
				&& street.matches("")
				&& city.matches("")
				&& region.matches("")
				&& zip.matches("")
				&& country.matches("")) {
			isValid = true;
		}
		
		return isValid;
	}
	
	public boolean validateDOB(String dob) {
		return dob.matches("^[0-9]{4}-[0-9]{2}-[0-9]{2}$");
	}
	*/
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		// added labels for address fields
		cityLabel = new JLabel();
		stateLabel = new JLabel();
		zipCodeLabel = new JLabel();
		countryLabel = new JLabel();

		//added a text box for Date of birth
		txtDob = new JTextField();

		// added text fields for address fields
		txtCity = new JTextField();
		txtState = new JTextField();
		txtZipCode = new JTextField();
		txtCountry = new JTextField();
		txtStreetAddress = new JTextField();

		jPanel1 = new JPanel();
		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		jLabel4 = new JLabel();
		jLabel5 = new JLabel();
		txtlastname = new JTextField();
		txtfirstname = new JTextField();
		txtnic = new JTextField();
		txtpassport = new JTextField();
		jScrollPane1 = new JScrollPane();
		jLabel6 = new JLabel();
		txtid = new JLabel();
		jPanel2 = new JPanel();
		jLabel8 = new JLabel();
		jLabel9 = new JLabel();
		jLabel10 = new JLabel();
		r1 = new JRadioButton();
		r2 = new JRadioButton();
		bgroup = new ButtonGroup();
		bgroup.add(r1);
		bgroup.add(r2);
		txtcontact = new JTextField();
		txtphoto = new JLabel();
		jButton1 = new JButton();
		jButton2 = new JButton();
		jButton3 = new JButton();

		jPanel1.setBackground(new Color(51, 0, 255));

		jLabel1.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setForeground(new Color(255, 255, 255));
		jLabel1.setText("FirstName");

		jLabel2.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setForeground(new Color(255, 255, 255));
		jLabel2.setText("LastName");

		jLabel3.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setForeground(new Color(255, 255, 255));
		jLabel3.setText("Nic No");

		jLabel4.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setForeground(new Color(255, 255, 255));
		jLabel4.setText("Passport ID");

		jLabel5.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel5.setForeground(new Color(255, 255, 255));
		jLabel5.setText("Address");

		cityLabel.setText("City");
		cityLabel.setForeground(Color.white);
		cityLabel.setFont(new Font("Tahoma", Font.BOLD, 11));

		zipCodeLabel.setText("Zip code");
		zipCodeLabel.setFont(new Font("Tahoma", Font.BOLD, 11));
		zipCodeLabel.setForeground(Color.white);

		countryLabel.setText("Country");
		countryLabel.setForeground(Color.white);
		countryLabel.setFont(new Font("Tahoma", Font.BOLD, 11));

		stateLabel.setText("State");
		stateLabel.setFont(new Font("Tahoma", Font.BOLD, 11));
		stateLabel.setForeground(Color.white);

		txtlastname.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				txtlastnameActionPerformed(evt);
			}
		});

		txtpassport.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				txtpassportActionPerformed(evt);
			}
		});


		GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(26, 26, 26).addGroup(jPanel1Layout
						.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
								.createParallelGroup(Alignment.LEADING, false)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(47, 47, 47)
										.addComponent(txtfirstname))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(Alignment.LEADING)
												.addComponent(jLabel5).addComponent(jLabel4).addComponent(jLabel3)
												.addComponent(txtStreetAddress, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
												.addComponent(txtZipCode, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
												.addComponent(zipCodeLabel)
										)
										.addGap(38, 38, 38)
										.addGroup(jPanel1Layout
												.createParallelGroup(Alignment.LEADING, false)
												.addComponent(txtpassport)
												.addComponent(txtnic).addGroup(jPanel1Layout.createSequentialGroup()
														.addGap(10, 10, 10)
														.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
																.addComponent(txtCountry, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
																.addComponent(cityLabel, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
																.addComponent(txtCity, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
																.addComponent(countryLabel, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
														.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
																.addComponent(stateLabel, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
																.addComponent(txtState, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
														.addGap(28, 28, 28)))))
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2).addGap(48, 48, 48)
										.addComponent(txtlastname, GroupLayout.PREFERRED_SIZE, 195,
												GroupLayout.PREFERRED_SIZE))
										.addGap(0, 0, Short.MAX_VALUE))))
		);
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup()
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(37, 37, 37)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(txtfirstname, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(22, 22, 22)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtlastname, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(txtnic, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(txtpassport, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel5).addComponent(cityLabel).addComponent(stateLabel))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
							.addComponent(txtStreetAddress, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
									GroupLayout.PREFERRED_SIZE).addComponent(txtCity, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(txtState, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(zipCodeLabel).addComponent(countryLabel))
						.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(txtZipCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtCountry, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
		);

		jLabel6.setFont(new Font("Tahoma", 1, 18)); // NOI18N
		jLabel6.setText("Customer ID");

		txtid.setFont(new Font("Tahoma", 1, 20)); // NOI18N
		txtid.setForeground(new Color(255, 0, 0));
		txtid.setText("jLabel7");

		jPanel2.setBackground(new Color(51, 0, 255));

		jLabel8.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel8.setForeground(new Color(255, 255, 255));
		jLabel8.setText("Date of Birth");

		jLabel9.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel9.setForeground(new Color(255, 255, 255));
		jLabel9.setText("Gender");

		jLabel10.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabel10.setForeground(new Color(255, 255, 255));
		jLabel10.setText("Contact");

		r1.setText("Male");
		r2.setText("Female");

		GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(22, 22, 22).addGroup(jPanel2Layout
						.createParallelGroup(Alignment.LEADING, false).addGroup(jPanel2Layout.createSequentialGroup()
								.addComponent(jLabel8).addGap(18, 18, 18)
						.addComponent(txtDob))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(jLabel9).addComponent(jLabel10))
								.addGap(43, 43, 43)
								.addGroup(jPanel2Layout
										.createParallelGroup(Alignment.LEADING, false)
										.addGroup(jPanel2Layout.createSequentialGroup().addComponent(r1)
												.addGap(18, 18, 18).addComponent(r2))
										.addComponent(txtcontact))))
						.addContainerGap(41, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(34, 34, 34)
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(txtDob, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel9).addComponent(r1).addComponent(r2))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel10).addComponent(txtcontact, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(108, Short.MAX_VALUE)));

		txtphoto.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));

		jButton1.setText("Browse");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Add");
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Cancel");
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(25, 25, 25).addComponent(jLabel6)
								.addGap(50, 50, 50).addComponent(txtid))
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(18, 18, 18).addGroup(layout
												.createParallelGroup(Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(txtphoto,
																GroupLayout.PREFERRED_SIZE, 250,
																GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup().addGap(337, 337, 337)
														.addComponent(jButton1, GroupLayout.PREFERRED_SIZE,
																87, GroupLayout.PREFERRED_SIZE))))
										.addGroup(layout.createSequentialGroup().addGap(39, 39, 39)
												.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 105,
														GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 100,
														GroupLayout.PREFERRED_SIZE)))))
				.addContainerGap(24, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(
				Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(txtid))
						.addGap(41, 41, 41)
						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup().addGap(25, 25, 25)
										.addGroup(layout
												.createParallelGroup(Alignment.LEADING, false)
												.addComponent(txtphoto, GroupLayout.DEFAULT_SIZE, 250,
														Short.MAX_VALUE)
												.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 33,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 38,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 38,
														GroupLayout.PREFERRED_SIZE))))
						.addGap(49, 49, 49)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtlastnameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtlastnameActionPerformed

	private void txtpassportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtpassportActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtpassportActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		String path;

		try {
			BufferedImage image = ImageOperations.chooseImage();
			ImageIcon icon = ImageOperations.imageToIcon(image);
			txtphoto.setIcon(icon);
			userimage = ImageOperations.imageToByteArray(image);

		} catch (IOException ex) {
			Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		String id = txtid.getText();
		String firstname = txtfirstname.getText();
		String lastname = txtlastname.getText();
		String nic = txtnic.getText();
		String passport = txtpassport.getText();
		String streetAddress = txtStreetAddress.getText();
		String city = txtCity.getText();
		String state = txtState.getText();
		String zipCode = txtZipCode.getText();
		String country = txtCountry.getText();
		// TODO Fix date of birth when field is added to GUI
		DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
		//		String date = da.format(txtdob.getDate());

		String date = txtDob.getText();
		String gender = r1.isSelected() ? "Male" : "Female";
		String contact = txtcontact.getText();

		try {
			Address address = new Address(streetAddress, city, state, zipCode, country);
			Customer customer = new Customer(id, firstname, lastname, nic,
					passport, address, date, gender, contact, userimage);
			cDao.add(customer);
			JOptionPane.showMessageDialog(this, "Registation Created.");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}

	}// GEN-LAST:event_jButton2ActionPerformed
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		this.hide();
	}// GEN-LAST:event_jButton3ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JRadioButton r1;
	private javax.swing.JRadioButton r2;
	private javax.swing.ButtonGroup bgroup;
	private javax.swing.JTextField txtStreetAddress;
	private javax.swing.JTextField txtcontact;
	private javax.swing.JTextField txtfirstname;
	private javax.swing.JLabel txtid;
	private javax.swing.JTextField txtlastname;
	private javax.swing.JTextField txtnic;
	private javax.swing.JTextField txtpassport;
	private javax.swing.JLabel txtphoto;
	private javax.swing.JLabel cityLabel;
	private javax.swing.JLabel stateLabel;
	private javax.swing.JLabel zipCodeLabel;
	private javax.swing.JLabel countryLabel;
	private javax.swing.JTextField txtCity;
	private javax.swing.JTextField txtState;
	private javax.swing.JTextField txtZipCode;
	private javax.swing.JTextField txtCountry;
	private javax.swing.JTextField txtDob;
	// End of variables declaration//GEN-END:variables
}
